#ifndef CONFIG_H
#define CONFIG_H

#include <p24FJ64GB002.h>

#define PIN_BUS_TXEN LATBbits.LATB9
#define PIN_ADDR_SWITCH PORTA

//#define MODULE_LIGHTSENSOR
//#define MODULE_LIGHTOUTPUT
#define MODULE_TANKSENSOR

#define NETWORK_ADDRESS 20

#endif
